#!/bin/bash

# Test script for veas-cli realtime functionality

echo "Testing veas-cli realtime task detection..."
echo "============================================"
echo ""
echo "To test realtime detection:"
echo ""
echo "1. In one terminal, run the destination watcher:"
echo "   npx veas dest watch <destination-id> --verbose"
echo ""
echo "2. In another terminal, create a test execution:"
echo "   Run this SQL in Supabase Studio or psql:"
echo ""
echo "   INSERT INTO agents.executions ("
echo "     task_id,"
echo "     status,"
echo "     trigger,"
echo "     trigger_source,"
echo "     input_params,"
echo "     queued_at"
echo "   ) VALUES ("
echo "     '<your-task-id>',"
echo "     'pending',"
echo "     'manual',"
echo "     'test-realtime',"
echo "     '{}'::jsonb,"
echo "     NOW()"
echo "   );"
echo ""
echo "3. Expected behavior:"
echo "   - The watcher should detect the execution within 1 second"
echo "   - You should see: '🔍 New unassigned execution detected: <execution-id>'"
echo "   - The execution should be claimed and processed immediately"
echo ""
echo "4. If realtime is working, you'll see the execution picked up instantly."
echo "   If only polling is working, it will take up to 30 seconds."
echo ""
echo "Look for these success messages:"
echo "  ✓ Subscribed to assigned executions (realtime)"
echo "  ✓ Subscribed to unassigned executions (realtime)"
echo "  ✓ Subscribed to schedule updates (realtime)"
echo ""
echo "If you see these warnings instead, realtime failed to connect:"
echo "  ⚠ Failed to subscribe to assigned executions, using polling only"
echo "  ⚠ Failed to subscribe to unassigned executions, using polling only"
echo "  ⚠ Failed to subscribe to schedules, using polling only"